GET http://localhost:3000/home

###

GET http://localhost:3000/teste


###

POST http://localhost:3000/cadastro
Content-Type:application/json

{
    "nome": "Joel Santos",
    "contato": "40028922",
    "idade": "18"
}